export const DashboardTypes = {
  RETRIEVE_REQUEST_SUMMARY: "RETRIEVE_REQUEST_SUMMARY",
  RETRIEVE_REQUESTSTATUS_SUMMARY: "RETRIEVE_REQUESTSTATUS_SUMMARY",
  RETRIEVE_GRID_DETAILS: "RETRIEVE_GRID_DETAILS",
  REMOVE_REQUEST_SUMMARY: "REMOVE_REQUEST_SUMMARY",
  REMOVE_REQUESTSTATUS_SUMMARY: "REMOVE_REQUESTSTATUS_SUMMARY",
  REMOVE_GRID_DETAILS: "REMOVE_GRID_DETAILS",
  GET_COUNTS: "GET_COUNTS",
};
