export const RequestTypes = {
  ADD_REQUEST_SUCCESSFUL: "ADD_REQUEST_SUCCESSFUL",
  ADD_REQUEST_FAILED: "ADD_REQUEST_FAILED",
  GET_CLIENT_DETAILS: "GET_CLIENT_DETAILS",
  REMOVE_CLIENT_DETAILS: "REMOVE_CLIENT_DETAILS",
};
