export const OrderTypes = {
  RETRIEVE_ORDER_SUMMARY: "RETRIEVE_ORDER_SUMMARY",
  ADD_ORDER_SUCCESSFUL: "ADD_ORDER_SUCCESSFUL",
  ADD_ORDER_FAILED: "ADD_ORDER_FAILED",
  SELECTED_ORDER: "SELECTED_ORDER",
  REMOVE_SELECTED_ORDER: "REMOVE_SELECTED_ORDER",
  CERTIFICATE_URL: "CERTIFICATE_URL",
  REMOVED_CERTIFICATE_URL: "REMOVED_CERTIFICATE_URL",
};
